<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.2.9.0</Version>
    <Author>Jacob5800</Author>
    <Name>Retainer Pricer</Name>
    <Punchline>Automatically price new and existing retainer listings.</Punchline>
    <Description>Automatically price eligible inventory and reprice existing listings one gil below matching competition using Universalis market prices and recent sale history.</Description>
    <RepoUrl>https://github.com/Jacob5800/RetainerPricer</RepoUrl>
    <Tags>retainer;marketboard;prices;universalis</Tags>
    <OutputPath>$(MSBuildProjectDirectory)\dist\$(Configuration)\</OutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="checks/**/*.cs" />
  </ItemGroup>
  <Target Name="PackagePlugin" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <DalamudPackager ProjectDir="$(ProjectDir)" OutputPath="$(OutputPath)" AssemblyName="$(AssemblyName)" MakeZip="true" />
  </Target>
</Project>
